### ISSUE TITLE
Does not work on latest unrealircd

### ISSUE THREAD

**Issue by dwaaan** [acidvegas/limitserv#1]
03:14:02 | [~] - :irc.----.net NOTICE * :*** Looking up your hostname...
03:14:02 | [~] - :irc.----.net NOTICE * :*** Found your hostname (cached)
03:14:03 | [!] - Error occured in the queue loop! ('IRC' object has no attribute '_raw')
03:14:03 | [!] - Error occured in the queue loop! ('IRC' object has no attribute '_raw')
03:14:04 | [!] - Error occured in the queue loop! ('IRC' object has no attribute '_raw')

**Comment by acidvegas** [comment]
Change Bot._raw to Command._raw in the def _queue() func.
Will fix on next commit
